  export const authors = [
  { id: "all", name: "View All", postCount: 6 },
  { id: "ashwani", name: "Dr. Ashwani Mahajan", postCount: 2, role: "Economics Professor" },
  { id: "surya", name: "Dr. Surya Prakash Agarwal", postCount: 1, role: "Political Analyst" },
  { id: "bhagwat", name: "Dr. Bhagwat Ram Agarwal", postCount: 1, role: "History Scholar" },
  { id: "devindra", name: "Devindra Sharma", postCount: 1, role: "Environmental Writer" },
  { id: "gurumurthy", name: "S. Gurumurthy", postCount: 0, role: "Columnist" },
  { id: "alok", name: "Alok Singh", postCount: 0, role: "Technology Expert" },
  { id: "kk", name: "KK Srivastava", postCount: 0, role: "Foreign Affairs Analyst" },
  { id: "jaya", name: "Dr. Jaya Kakkar", postCount: 0, role: "Health Specialist" },
  { id: "vandana", name: "Dr. Vandana Shiva", postCount: 1, role: "Environmental Activist" },
  { id: "anil", name: "Anil Tiwari", role: "Educationist", posts: 14 },
  { id: "bhagwati", name: "Prof. Bhagwati Prakash Sharma", role: "Sociology Professor", posts: 26 },
  { id: "indra", name: "Indra Shekhar Singh", role: "Agriculture Expert", posts: 19 },
  { id: "vinod", name: "Vinod Johri", role: "Business Analyst", posts: 22 },
  { id: "nandini", name: "Prof. Nandini Kapur Sinha", role: "Literature Professor", posts: 16 },
  { id: "mahadevyya", name: "Mahadevyya Karadalli", role: "Cultural Writer", posts: 13 },
  { id: "vikram", name: "Vikram Upadhyay", role: "Legal Analyst", posts: 20 },
  { id: "javalekar", name: "Anil Javalekar", role: "Science Communicator", posts: 11 },
  { id: "vamraj", name: "Dr. Vamraj Kumar", role: "Medical Researcher", posts: 25 },
  { id: "sharma", name: "Dr. Jaya Sharma", role: "Gender Studies Expert", posts: 18 },
  { id: "dinesh", name: "Dr. Dinesh Prasad Mishra", role: "Public Policy Analyst", posts: 23 },
  { id: "bharat", name: "Bharat Dogra", role: "Development Journalist", posts: 35 },
  { id: "prahlad", name: "Prahlad Sabnani", role: "Art Critic", posts: 14 },
  { id: "lingamurthy", name: "Dr. S. Lingamurthy", role: "Linguistics Professor", posts: 17 },
  { id: "shivanand", name: "Shivanand Lal", role: "Philosophy Writer", posts: 16 },
  { id: "swadesh", name: "Swadesh Samvad", role: "Media Collective", posts: 28 },
  { id: "vikas", name: "Vikas Sinha", role: "Investigative Journalist", posts: 19 },
  { id: "sumit", name: "Dr. Sumit Dahiya", role: "Climate Scientist", posts: 22 },
  { id: "dulichand", name: "Dulichand Kaliraman", role: "Folklore Researcher", posts: 15 },
];
